=== toth152/WTX6LW_XMLgyak/WTX6LW_0929/WTX6LW_konyv.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT konyvek (konyv+)>

<!ATTLIST konyv id CDATA #REQUIRED>  

<!ELEMENT konyv (cim,ev,kiado,szerzo+)>

<!ELEMENT cim (#PCDATA)>
<!ELEMENT ev (#PCDATA)>
<!ELEMENT kiado (#PCDATA)>
<!ELEMENT szerzo (#PCDATA)>

=== toth152/WTX6LW_XMLgyak/WTX6LW_0929/WTX6LW_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE konyv SYSTEM "WTX6LW_konyv.dtd">

<konyvek>
	<konyv id="k_1">
		<cim>Java Programozas</cim>
		<ev>2010</ev>
		<kiado>Kiado_1</kiado>
		<szerzo>Szerzo1</szerzo>
	</konyv>
	<konyv id="k_2">
		<cim>C++ Programozas</cim>
		<ev>2011</ev>
		<kiado>Kiado_2</kiado>
		<szerzo>Szerzo1, Szerzo2</szerzo>
	</konyv>
	<konyv id="k_3">
		<cim>Python Programozas</cim>
		<ev>2012</ev>
		<kiado>Kiado_3</kiado>
		<szerzo>Szerzo3</szerzo>
	</konyv>
</konyvek>
