=== toth152/WTX6LW_XMLgyak/WTX6LW_1006/WTX6LW_ertoxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.example.org/KM_dtdtoxml" elementFormDefault="qualified">
    
    <xs:element name="convert">
        
        <xs:complexType>
            <xs:sequence>
                <xs:element name="A" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="Ab">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Abx"/>
                                        <xs:element name="Aby"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Ac">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Acd" type="xs:string"/>
                                        <xs:element name="Ace" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Aa" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="B" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="Bb">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Bbx" type="xs:string"/>
                                        <xs:element name="Bby" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Ba" type="xs:string"/>
                        <xs:attribute name="B_C" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="C" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="Cb" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="Ca" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="A_B" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="A_B_c" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="A_B_A" type="xs:string"/>
                        <xs:attribute name="A_B_B" type="xs:string"/>
                    </xs:complexType>
                </xs:element> 
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== toth152/WTX6LW_XMLgyak/WTX6LW_1006/WTX6LW_xsdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<convert xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="WTX6LW_ertoxsd.xsd">
    
    <A Aa="A_1">
        <Ab>
            <Abx></Abx>
            <Aby></Aby>
        </Ab>
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>

    <B Ba="B_1" B_C="B_2">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>

    <C Ca="C_1">
        <Cb></Cb>
    </C>

    <A_B A_B_A="AB_1" A_B_B="AB_2">
        <A_B_c></A_B_c>
    </A_B>
</convert>
