=== toth152/WTX6LW_XMLgyak/WTX6LW_1020/macskakWTX6LW.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT macskak (macska+)>

<!ATTLIST macska id ID #REQUIRED>

<!ELEMENT macska (nev, kor, fajta)>
		
<!ELEMENT nev (#PCDATA)>
<!ELEMENT kor (#PCDATA)>
<!ELEMENT fajta (#PCDATA)>

=== toth152/WTX6LW_XMLgyak/WTX6LW_1020/SAXWTX6LW/src/SAXWTX6LW1020/macskakWTX6LW.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--<!DOCTYPE macskak SYSTEM "macskakWTX6LW.dtd">-->

<!--  <macskak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="macskakWTX6LW.xsd"> -->

<macskak>
	<macska id="m1">
		<nev>Cirmi</nev>
		<kor>2</kor>
		<fajta>Cirmos</fajta>
	</macska>
	<macska id="m2">
		<nev>Kormos</nev>
		<kor>5</kor>
		<fajta>Keverek</fajta>
	</macska>
	<macska id="m3">
		<nev>Vakarcs</nev>
		<kor>1</kor>
		<fajta>Sziami</fajta>
	</macska>
</macskak>
